num1=input("enter a number:")
int(num1)
print(num1)
num2=input("how many cash do you want to deposit?")
float(num2)
print(num2)
num3=input("imagine a float number")
int(num3)
print(num3)
num4=input("how many?")
float(num4)
print(num4)
num5=input("turn int into float")
float(num5)
print(num5)
num6=input("just put a float")
int(num6)
print(num6)